### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by littleskunk** [StorjOld/pyp2p#37]
Tested with storjnode develop branch and pyp2p 0.8.0
Windows don't has this problem. 

I am running storjnode on my linux NAS in a LXC "VM". The reason for the error could be the firewall of the NAS. I don't know if the NAS comes with a simple NAT firewall.

less error.log

```
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
 <class 'socket.error'> sock.py 195 [Errno 111] Connection refused
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/pyp2p/sock.py", line 195, in connect
    self.s.connect((addr, int(port)))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
 <class 'socket.error'> sock.py 195 [Errno 111] Connection refused
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/pyp2p/sock.py", line 195, in connect
    self.s.connect((addr, int(port)))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
 <class 'socket.error'> sock.py 195 [Errno 111] Connection refused
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/pyp2p/sock.py", line 195, in connect
    self.s.connect((addr, int(port)))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
 <class 'socket.error'> sock.py 195 [Errno 111] Connection refused
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/pyp2p/net.py", line 654, in determine_node
    lan_ip)
  File "build/bdist.linux-x86_64/egg/pyp2p/upnp.py", line 203, in forward_port
    raise Exception("Unable to find UPnP compatible gateway.")
Exception: Unable to find UPnP compatible gateway.
 <type 'exceptions.Exception'> net.py 654 Unable to find UPnP compatible gateway.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/pyp2p/net.py", line 674, in determine_node
    lan_ip)
  File "build/bdist.linux-x86_64/egg/pyp2p/nat_pmp.py", line 482, in forward_port
    return map_port(proto, src_port, dest_port)
  File "build/bdist.linux-x86_64/egg/pyp2p/nat_pmp.py", line 413, in map_port
    retry=retry)
  File "build/bdist.linux-x86_64/egg/pyp2p/nat_pmp.py", line 454, in send_request_with_retry
    error_str(NATPMP_GATEWAY_NO_SUPPORT))
NATPMPUnsupportedError: (-11, 'The gateway does not support NAT-PMP')
 <class 'pyp2p.nat_pmp.NATPMPUnsupportedError'> net.py 674 (-11, 'The gateway does not support NAT-PMP')
```

**Comment by littleskunk** [comment]
Same problem with osx.

**Comment by robertsdotpm** [comment]
This means that the automated port forwarding failed with UPnP and NATPMP. As long as the software is still running it can work without it.
